import type { Place } from "@/lib/notion/types";

export const places: Place[] = [
  {
    id: "place-001",
    slug: "central-market-noodle",
    title: "중앙시장 칼국수집",
    category: "food",
    lat: 37.5662,
    lng: 127.0198,
    address: "서울 중구 퇴계로85길",
    summary: "비 오는 날 생각나는 손칼국수와 겉절이의 단정한 조합.",
    cover: { url: "warm-table", alt: "따뜻한 국수 한 그릇" },
    tags: ["노포", "혼밥", "점심"],
    status: "published",
    updatedAt: "2026-05-16T00:00:00.000Z",
  },
  {
    id: "place-002",
    slug: "sindang-roastery",
    title: "신당 로스터리",
    category: "cafe",
    lat: 37.5653,
    lng: 127.0169,
    address: "서울 중구 다산로",
    summary: "골목 안쪽에서 볶는 원두 향과 낮은 음악이 오래 남는 카페.",
    cover: { url: "coffee-light", alt: "햇빛이 들어오는 커피 바" },
    tags: ["로스터리", "작업", "디저트"],
    status: "published",
    updatedAt: "2026-05-16T00:00:00.000Z",
  },
  {
    id: "place-003",
    slug: "small-stage-sindang",
    title: "소극장 신당",
    category: "culture",
    lat: 37.5671,
    lng: 127.0148,
    address: "서울 중구 난계로",
    summary: "주말 저녁의 독립 공연과 전시 소식이 모이는 작은 무대.",
    cover: { url: "gallery-room", alt: "작은 전시 공간" },
    tags: ["공연", "전시", "주말"],
    status: "published",
    updatedAt: "2026-05-16T00:00:00.000Z",
  },
  {
    id: "place-004",
    slug: "yellow-stair-alley",
    title: "노란 계단 골목",
    category: "place",
    lat: 37.5644,
    lng: 127.0216,
    address: "서울 중구 신당동 골목",
    summary: "낮게 이어지는 주택가와 시장 소리가 만나는 산책 코스.",
    cover: { url: "alley-sun", alt: "오후 햇살이 드는 골목" },
    tags: ["산책", "사진", "골목"],
    status: "published",
    updatedAt: "2026-05-16T00:00:00.000Z",
  },
  {
    id: "place-005",
    slug: "late-night-dumpling",
    title: "밤만두",
    category: "food",
    lat: 37.5637,
    lng: 127.0184,
    address: "서울 중구 청구로",
    summary: "늦은 시간에도 불이 켜져 있는 찐만두와 맑은 국물.",
    cover: { url: "night-kitchen", alt: "밤의 작은 식당" },
    tags: ["야식", "포장", "만두"],
    status: "published",
    updatedAt: "2026-05-16T00:00:00.000Z",
  },
  {
    id: "place-006",
    slug: "quiet-yard-cafe",
    title: "조용한 마당",
    category: "cafe",
    lat: 37.568,
    lng: 127.0207,
    address: "서울 중구 동호로",
    summary: "작은 마당석에 앉아 신당의 오후를 천천히 보는 곳.",
    cover: { url: "yard-cafe", alt: "작은 마당이 있는 카페" },
    tags: ["마당", "커피", "대화"],
    status: "published",
    updatedAt: "2026-05-16T00:00:00.000Z",
  },
];

export function getPlaceBySlug(slug: string): Place | undefined {
  return places.find((p) => p.slug === slug);
}
